Add retry logic with exponential backoff to API client
hackmdio/api-client pull request #30
Opened 2024-08-08 12:48 UTC by Taombawkry

Add retry logic with exponential backoff to API client:
- Implemented retry interceptor for handling transient errors.
- Added exponential backoff mechanism with a base delay of 100ms.
- Updated error handling to include retryable conditions (5xx and 429).

[#382](https://github.com/hackmdio/hackmd-io-issues/issues/382)

2024-09-06 07:24 UTC, Yukaii requested changes

2024-09-06 09:37 UTC, Taombawkry reviewed
Comments Addressed

2024-09-06 09:37 UTC, Taombawkry commented on nodejs/src/index.ts
> +      timeout: 30000, // Increased timeout for low bandwidth
APIClient options type has been expand and methods have been made options of it.

2024-09-06 09:37 UTC, Taombawkry commented on nodejs/src/index.ts
> +  constructor (
Constructor is easier to read this way

2024-09-06 09:37 UTC, Taombawkry commented on nodejs/src/index.ts
> +      error.response.status === 429
Added a mechanism to check API rate limits (`x-ratelimit-userlimit`, `x-ratelimit-userremaining`) and trigger retries or failures based on remaining credits.

2024-09-27 10:17 UTC, Yukaii approved these changes

2024-10-11 06:25 UTC, merged